import { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import { getDonationById } from "../../utils/api_request/donations";
import { getNgoConfig } from "../../utils/api_request/ngo";
import { useApp } from "../../context/AppContext";
import type { Donation } from "../../types/donation";
import type { CertificateData } from "../../components/CertificateCanvas";

export const useCertificateView = () => {
    const { id } = useParams<{ id: string }>();
    const { ngoConfig } = useApp();

    const [donation, setDonation] = useState<Donation | null>(null);
    const [isLoading, setIsLoading] = useState(true);
    const [notFound, setNotFound] = useState(false);
    const [certificateData, setCertData] = useState<CertificateData | null>(
        null,
    );

    useEffect(() => {
        if (!id) return;
        loadDonation(id);
    }, [id]);

    const loadDonation = async (donationId: string) => {
        setIsLoading(true);
        setNotFound(false);
        try {
            const [data, freshConfig] = await Promise.all([
                getDonationById(donationId),
                getNgoConfig().catch(() => ngoConfig),
            ]);
            setDonation(data);
            const activeConfig = freshConfig || ngoConfig;
            setCertData({
                ngoName: activeConfig.name,
                ngoLogo: activeConfig.logoUrl,
                ngoAddress: activeConfig.address,
                ngoEmail: activeConfig.email,
                registrationNumber: activeConfig.registrationNumber,
                presidentName: activeConfig.presidentName,
                secretaryName: activeConfig.secretaryName,
                signatureUrl: activeConfig.signatureUrl,
                donorName: data.donorName,
                amount: data.amount,
                donationDate: data.requestedAt,
                // Use the official certificate number generated by the backend on approval
                certificateNumber: data.certificateNumber || "",
                purpose: "General NGO Activities",
            });
        } catch {
            setNotFound(true);
        } finally {
            setIsLoading(false);
        }
    };

    return { donation, certificateData, isLoading, notFound, ngoConfig };
};

export type ReturnTypeOfUseCertificateView = ReturnType<
    typeof useCertificateView
>;
