import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { getDonationById } from '../../utils/api_request/donations';
import { useApp } from '../../context/AppContext';
import type { Donation } from '../../types/donation';
import type { CertificateData } from '../../components/CertificateCanvas';

export const useCertificateView = () => {
  const { id }        = useParams<{ id: string }>();
  const { ngoConfig } = useApp();

  const [donation, setDonation]         = useState<Donation | null>(null);
  const [isLoading, setIsLoading]       = useState(true);
  const [notFound, setNotFound]         = useState(false);
  const [certificateData, setCertData]  = useState<CertificateData | null>(null);

  useEffect(() => {
    if (!id) return;
    loadDonation(id);
  }, [id]);

  const loadDonation = async (donationId: string) => {
    setIsLoading(true);
    setNotFound(false);
    try {
      const data = await getDonationById(donationId);
      setDonation(data);
      setCertData({
        ngoName:            ngoConfig.name,
        ngoLogo:            ngoConfig.logoUrl,
        ngoAddress:         ngoConfig.address,
        ngoEmail:           ngoConfig.email,
        registrationNumber: ngoConfig.registrationNumber,
        presidentName:      ngoConfig.presidentName,
        secretaryName:      ngoConfig.secretaryName,
        signatureUrl:       ngoConfig.signatureUrl,
        donorName:          data.donorName,
        amount:             data.amount,
        donationDate:       data.requestedAt,
        // Use the official certificate number generated by the backend on approval
        certificateNumber:  data.certificateNumber || '',
        purpose:            'General NGO Activities',
      });
    } catch {
      setNotFound(true);
    } finally {
      setIsLoading(false);
    }
  };

  return { donation, certificateData, isLoading, notFound, ngoConfig };
};

export type ReturnTypeOfUseCertificateView = ReturnType<typeof useCertificateView>;
